load "Parser.rb"
parse1 = Parser.new("input4.tiny")
parse1.program()
parse2 = Parser.new("input5.tiny")
parse2.program()
parse3 = Parser.new("input4.tiny")
parse3.program()
parse4 = Parser.new("input4.tiny")
parse4.program()
parse5 = Parser.new("input5.tiny")
parse5.program()